[package]
name = "capnp-test"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
chrono = "0.4"
rand = "0.9.0"

[build-dependencies]
capnpc = "0.18"
