[package]
name = "test-rayon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
futures = "0.3.30"
rayon = "1.10.0"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
