[package]
name = "test-pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genpdf = { version = "0.2.0", features = ["image", "images", "hyphenation"] }
