[package]
name = "test-gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = "4.3.11"
llm = { git = "https://github.com/rustformers/llm" , branch = "main", features=["falcon"] }
rand = "0.8.5"
rustyline = "12.0.0"
tokio = { version = "1.29.1", features = ["full"] }
