[package]
name = "test-mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
dotenv = "0.15.0"
futures-util = "0.3.28"
mongodb = "2.6.0"
tokio = "1.29.1"
tokio-stream = "0.1.14"
