server2:
	cargo run --release --example h3server --  --listen "[::1]:4433"

server:
	cargo run --release --example h3server -- --listen=127.0.0.1:4433

client:
	cargo run --release --example h3client -- https://localhost:4433

