[package]
name = "test-bindings"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow="1.0"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"


[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
