all: install
	npx hardhat run ./scripts/hello.ts --network cronosZkEvmTestnet

install:
	npm i

wallet:
	npx hardhat run ./scripts/wallet.ts --network cronosZkEvmTestnet

compile:
	npx hardhat compile
