// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xd1d3f48382ab2e4d");
export class Book extends $.Struct {
  static readonly _capnp = {
    displayName: "Book",
    id: "ec67e3f4ae8db1bc",
    size: new $.ObjectSize(8, 3)
  };
  get title(): string {
    return $.utils.getText(0, this);
  }
  set title(value: string) {
    $.utils.setText(0, value, this);
  }
  get author(): string {
    return $.utils.getText(1, this);
  }
  set author(value: string) {
    $.utils.setText(1, value, this);
  }
  get pages(): number {
    return $.utils.getUint32(0, this);
  }
  set pages(value: number) {
    $.utils.setUint32(0, value, this);
  }
  get publishYear(): number {
    return $.utils.getUint16(4, this);
  }
  set publishYear(value: number) {
    $.utils.setUint16(4, value, this);
  }
  _adoptGenres(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownGenres(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.genres);
  }
  get genres(): $.List<string> {
    return $.utils.getList(2, $.TextList, this);
  }
  _hasGenres(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initGenres(length: number): $.List<string> {
    return $.utils.initList(2, $.TextList, length, this);
  }
  set genres(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get isAvailable(): boolean {
    return $.utils.getBit(48, this);
  }
  set isAvailable(value: boolean) {
    $.utils.setBit(48, value, this);
  }
  toString(): string {
    return "Book_" + super.toString();
  }
}
export class Fruit extends $.Struct {
  static readonly _capnp = {
    displayName: "Fruit",
    id: "ecfdc1d6d3ec158a",
    size: new $.ObjectSize(8, 3)
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get color(): string {
    return $.utils.getText(1, this);
  }
  set color(value: string) {
    $.utils.setText(1, value, this);
  }
  get weightGrams(): number {
    return $.utils.getUint32(0, this);
  }
  set weightGrams(value: number) {
    $.utils.setUint32(0, value, this);
  }
  get isRipe(): boolean {
    return $.utils.getBit(32, this);
  }
  set isRipe(value: boolean) {
    $.utils.setBit(32, value, this);
  }
  get variety(): string {
    return $.utils.getText(2, this);
  }
  set variety(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string {
    return "Fruit_" + super.toString();
  }
}
export const Message_Which = {
  BOOK: 0,
  FRUIT: 1
} as const;
export type Message_Which = (typeof Message_Which)[keyof typeof Message_Which];
export class Message extends $.Struct {
  static readonly BOOK = Message_Which.BOOK;
  static readonly FRUIT = Message_Which.FRUIT;
  static readonly _capnp = {
    displayName: "Message",
    id: "b7edb751df9abf98",
    size: new $.ObjectSize(8, 1)
  };
  _adoptBook(value: $.Orphan<Book>): void {
    $.utils.setUint16(0, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBook(): $.Orphan<Book> {
    return $.utils.disown(this.book);
  }
  get book(): Book {
    $.utils.testWhich("book", $.utils.getUint16(0, this), 0, this);
    return $.utils.getStruct(0, Book, this);
  }
  _hasBook(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBook(): Book {
    $.utils.setUint16(0, 0, this);
    return $.utils.initStructAt(0, Book, this);
  }
  get _isBook(): boolean {
    return $.utils.getUint16(0, this) === 0;
  }
  set book(value: Book) {
    $.utils.setUint16(0, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptFruit(value: $.Orphan<Fruit>): void {
    $.utils.setUint16(0, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownFruit(): $.Orphan<Fruit> {
    return $.utils.disown(this.fruit);
  }
  get fruit(): Fruit {
    $.utils.testWhich("fruit", $.utils.getUint16(0, this), 1, this);
    return $.utils.getStruct(0, Fruit, this);
  }
  _hasFruit(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initFruit(): Fruit {
    $.utils.setUint16(0, 1, this);
    return $.utils.initStructAt(0, Fruit, this);
  }
  get _isFruit(): boolean {
    return $.utils.getUint16(0, this) === 1;
  }
  set fruit(value: Fruit) {
    $.utils.setUint16(0, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Message_" + super.toString();
  }
  which(): Message_Which {
    return $.utils.getUint16(0, this) as Message_Which;
  }
}
export class BookList extends $.Struct {
  static readonly _capnp = {
    displayName: "BookList",
    id: "e907bff2d9f0122f",
    size: new $.ObjectSize(0, 1)
  };
  static _Books: $.ListCtor<Book>;
  _adoptBooks(value: $.Orphan<$.List<Book>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBooks(): $.Orphan<$.List<Book>> {
    return $.utils.disown(this.books);
  }
  get books(): $.List<Book> {
    return $.utils.getList(0, BookList._Books, this);
  }
  _hasBooks(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBooks(length: number): $.List<Book> {
    return $.utils.initList(0, BookList._Books, length, this);
  }
  set books(value: $.List<Book>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "BookList_" + super.toString();
  }
}
BookList._Books = $.CompositeList(Book);
