// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod hello_world {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum HelloOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Hello<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Hello<'a> {
  type Inner = Hello<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Hello<'a> {
  pub const VT_MESSAGE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Hello { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args HelloArgs<'args>
  ) -> flatbuffers::WIPOffset<Hello<'bldr>> {
    let mut builder = HelloBuilder::new(_fbb);
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }


  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Hello::VT_MESSAGE, None)}
  }
}

impl flatbuffers::Verifiable for Hello<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct HelloArgs<'a> {
    pub message: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for HelloArgs<'a> {
  #[inline]
  fn default() -> Self {
    HelloArgs {
      message: None,
    }
  }
}

pub struct HelloBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HelloBuilder<'a, 'b> {
  #[inline]
  pub fn add_message(&mut self, message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Hello::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HelloBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HelloBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Hello<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Hello<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Hello");
      ds.field("message", &self.message());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Hello`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_hello_unchecked`.
pub fn root_as_hello(buf: &[u8]) -> Result<Hello, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Hello>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Hello` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_hello_unchecked`.
pub fn size_prefixed_root_as_hello(buf: &[u8]) -> Result<Hello, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Hello>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Hello` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_hello_unchecked`.
pub fn root_as_hello_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Hello<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Hello<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Hello` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_hello_unchecked`.
pub fn size_prefixed_root_as_hello_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Hello<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Hello<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Hello and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Hello`.
pub unsafe fn root_as_hello_unchecked(buf: &[u8]) -> Hello {
  flatbuffers::root_unchecked::<Hello>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Hello and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Hello`.
pub unsafe fn size_prefixed_root_as_hello_unchecked(buf: &[u8]) -> Hello {
  flatbuffers::size_prefixed_root_unchecked::<Hello>(buf)
}
#[inline]
pub fn finish_hello_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Hello<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_hello_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Hello<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod HelloWorld

