[package]
name = "test-ai-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0.210", features = ["derive"] }
anyhow = "1.0.89"
