[package]
name = "test-capnp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
capnp = "0.20.6"
capnpc = "0.20.1"
fake = { version = "2.9", features = ["derive"] }
hex = "0.4.3"

[build-dependencies]
capnpc = "0.20.1"
