[package]
name = "test-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp-2 = "0.1"
hf-hub = { version="0.3" }
clap = {version="4.5" , features = ["derive"] }
anyhow = {version="1.0" }
encoding_rs = {version ="0.8"}
